from typing import Optional

import numpy as np

class LeDataError(Exception):
    """LEData 基础异常"""

class UnsupportedFormatError(LeDataError):
    """表格的格式不受支持"""

class EmptyDirError(LeDataError):
    """目录为空"""

class NoSupportedDataError(LeDataError):
    """目录下没有找到符合支持格式的数据表格"""

class InvalidPathError(LeDataError):
    """路径无效"""

class SpectrumPoint:
    """单点光谱：某器件在匹配电压索引处的切片"""
    @property
    def device_name(self) -> str: ...
    @property
    def slot(self) -> int: ...
    @property
    def requested_voltage(self) -> float: ...
    @property
    def matched_voltage(self) -> float: ...
    @property
    def matched_index(self) -> int: ...
    @property
    def wavelength(self) -> np.ndarray: ...
    @property
    def values(self) -> np.ndarray: ...
    def to_dict(self) -> dict: ...

class DeviceData:
    """器件数据对象；数组属性每次访问都返回拷贝"""
    @property
    def name(self) -> str: ...
    @property
    def is_vis(self) -> bool: ...
    @property
    def slot(self) -> int: ...
    @property
    def u(self) -> np.ndarray: ...
    @property
    def j(self) -> np.ndarray: ...
    @property
    def luminance(self) -> np.ndarray: ...
    @property
    def eqe(self) -> np.ndarray: ...
    @property
    def wavelength(self) -> np.ndarray: ...
    @property
    def spectra(self) -> np.ndarray: ...  # 2D, (n_u, n_wavelength)
    @property
    def max_j(self) -> float: ...
    @property
    def max_lumi(self) -> float: ...
    @property
    def max_eqe(self) -> float: ...
    @property
    def valid_eqe(self) -> float: ...
    @property
    def leak_j(self) -> float: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def spectrum_at(self, voltage: float) -> Optional[SpectrumPoint]: ...

class Chip:
    """器件玻片数据对象"""
    @property
    def name(self) -> str: ...
    @property
    def devices(self) -> "list[Optional[DeviceData]]": ...
    def summary(self, voltage: Optional[float] = None) -> dict: ...
    def spectra_at(self, voltage: float, site: Optional[str] = None) -> "list[SpectrumPoint]": ...
    def to_json(self) -> str: ...

class DirResult:
    """目录批量解析结果"""
    @property
    def chips(self) -> "list[Chip]": ...
    @property
    def warnings(self) -> "list[str]": ...
    @property
    def errors(self) -> "list[str]": ...

def parse_file(path: str) -> "tuple[Chip, Optional[str]]": ...
def parse_dir(path: str) -> DirResult: ...
